### ISSUE TITLE
Contact Page Layout & Styles

### ISSUE THREAD

**Issue by crobinson42** [wingchunkf/my-profile#12]
Create a contact form that a visitor to the site can complete and submit. This form should include information that the receiving party would find useful to know before responding to the contact request.

Topic reading: https://www.searchenginejournal.com/25-amazing-contact-us-pages/

Requirements: 

- Use bootstrap v3 (http://getbootstrap.com/) on all layout and form elements/components
- For now the form will only submit/POST to itself (contact.html) we'll setup some server side logic later to actually send the form somewhere in an email

Notes:

Be sure to include the minified bootstrap stylesheet in the repo instead of referencing a CDN link source. You can also include a second stylesheet (ie: contact.css) to apply overriding styles or extend the bootstrap styles.

**Comment by wingchunkf** [comment]
Completed contact page layout and css.
