### ISSUE TITLE
Add "recent work" page to site layout/styles

### ISSUE THREAD

**Issue by crobinson42** [wingchunkf/my-profile#17]
Create a page w/ layout & styles that will showcase multiple real world sites/examples of work done by Bergman. 

For now just use a placeholder "Coming soon" but complete the CSS to easily add projects in the near future to this page. 

The page layout should reflect the attached layout structure:
<img width="883" alt="screenshot 2017-07-11 11 08 33" src="https://user-images.githubusercontent.com/5973579/28083148-4c9c9afe-6629-11e7-9da1-aa5e98925fd7.png">

**Comment by wingchunkf** [comment]
Created page with placeholders for project thumbnails.
