### ISSUE TITLE
Mobile layout incompat

### ISSUE THREAD

**Issue by crobinson42** [wingchunkf/my-profile#7]
The site isn't mobile friendly 
![screenshot_20170707-141935](https://user-images.githubusercontent.com/5973579/27977435-a02cbd5a-631f-11e7-8707-d87d6ccd7829.png)

**Comment by crobinson42** [comment]
Recommend looking into a few css properties that would help resolve the issues in the screenshot:

- Use media queries to change the div containers to `display: block` when the screen size width is less than ~500px
- Look into using the `word-break` & `overflow` css properties for containers that have text going outside of their parent containers
- Use `min-width` & `max-width` on containers so they aren't infinitely smaller % of the screen (ie: if you were to shrink the screen down to 10px width, they are set to use % of that 10px... they would be **really** small at that point, so, you would not want them to shrink smaller than a certain width/height - you can still use % for `height` & `width` but you can also use `min-width` `max-width` in conjunction)

**Comment by wingchunkf** [comment]
Changed divs to display block and replaced background image with colored background for small screen sizes.  Closes issue #7.
